cluster.name: "logx-cluster"
network.host: 0.0.0.0

# 启用安全功能
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
xpack.security.transport.ssl.enabled: false  # 开发环境可禁用
xpack.security.http.ssl.enabled: false       # 开发环境可禁用

# 允许内置用户
xpack.security.authc:
  anonymous:
    username: anonymous
    roles: superuser
    authz_exception: false

# 内存设置
bootstrap.memory_lock: false